import type { NavOverlay } from "./types";

/**
 * GENERATED by `scripts/build-nav-overlay.ts` — do not edit `items` by hand.
 *
 * `items` is derived from each translated page's own frontmatter `title`, so a
 * sidebar label can never disagree with the page it opens. Re-run
 * `pnpm -F @nombaone/docs l10n:nav` after translating a page.
 *
 * `sections` IS hand-authored and is preserved across regeneration. Sections that
 * lead only to frozen-English pages keep their English titles on purpose.
 */
export const NAV_HA: NavOverlay = {
  sections: {
    "get-started": "Farawa",
    libraries: "Quickstart",
    sdks: "SDKs & CLI",
    guides: "Jagorori",
    cookbook: "Cookbook",
    concepts: "Raʼayoyi",
    "best-practices": "Hanyoyin da suka fi kyau",
    api: "API reference",
    webhooks: "Webhooks",
    errors: "Errors",
    "sandbox-toolkit": "Sandbox toolkit",
    changelog: "Release notes",
    migrate: "Ƙaura",
    agents: "Ga agents",
    merchants: "Ga ʼyan kasuwa",
  },
  items: {
    "/getting-started/authentication": { title: "Tantancewa" },
    "/getting-started/environments": { title: "Muhallai" },
    "/getting-started/your-first-subscription": { title: "Subscription naka na farko" },
    "/getting-started/verify-in-your-devtools": { title: "Tabbatar da mu a cikin devtools ɗinka" },
    "/getting-started/quickstart": { title: "Quickstart" },
    "/guides/create-plans-and-prices": { title: "Ƙirƙirar plan da price" },
    "/guides/start-a-subscription": { title: "Fara subscription" },
    "/guides/handle-webhooks": { title: "Sarrafa webhooks" },
    "/guides/dunning-and-recovery": { title: "Dunning da farfaɗowar biyan kuɗi" },
    "/guides/refunds-payouts-settlement": { title: "Refunds, payouts da settlement" },
    "/guides/proration-and-plan-changes": { title: "Proration da canje-canjen plan" },
    "/guides/coupons-and-credits": { title: "Coupon da credit" },
    "/guides/going-live": { title: "Komawa live" },
    "/concepts/how-billing-works": { title: "Yadda billing ke aiki" },
    "/concepts/money-is-integer-kobo": { title: "Kuɗi cikakkiyar lamba ce a kobo" },
    "/concepts/the-ledger": { title: "Ledger mai shigarwa biyu" },
    "/concepts/multi-rail-push-and-pull": { title: "Multi-rail: push da pull" },
    "/concepts/settlement-and-sub-accounts": { title: "Settlement da sub-accounts" },
    "/concepts/hard-parts": { title: "Sassan da suka fi wahala" },
    "/concepts/hard-parts/the-double-charge-bug": { title: "Matsalar caji sau biyu, da dalilin da ya sa idempotency key ba zaɓi ba ne" },
    "/concepts/hard-parts/dunning-for-thin-balances": { title: "Dunning don balance mara kuɗi: dalilin da ya sa sake gwadawa a ranar albashi ke fin tsayayyen jadawali" },
    "/concepts/hard-parts/bank-transfer-is-not-just-another-method": { title: "Me ya sa bank transfer ba wata hanyar biya kawai ba ce" },
    "/concepts/hard-parts/card-tokens-expire": { title: "Card token yana ƙarewa, kuma dalilin da ya sa sake gwadawa a makance ke ɓata lokacin dunning naka" },
    "/concepts/hard-parts/when-a-transfer-does-not-match-the-invoice": { title: "Lokacin da kuɗin da aka tura bai yi daidai da adadin invoice ba" },
    "/concepts/hard-parts/retry-the-webhook-is-not-retry-the-charge": { title: "\"Sake aika webhook\" ba shi ne \"sake gwada charge\" ba" },
    "/concepts/hard-parts/mandates-and-consent": { title: "Mandate da yarda: siffar bin ƙaʼida ta direct debit" },
    "/concepts/hard-parts/proration-is-a-ledger-problem": { title: "Proration matsalar ledger ce, ba matsalar lissafi ba" },
    "/concepts/hard-parts/the-end-of-month-billing-trap": { title: "Tarkon biyan kuɗi na ƙarshen wata (matsalar 31 ga Janairu)" },
    "/concepts/hard-parts/voluntary-vs-involuntary-churn": { title: "Ficewa da gangan da ficewa ba da gangan ba, da dalilin da ya sa haɗa su ke ɓata maʼaunanka" },
    "/concepts/hard-parts/settlement-without-spreadsheets": { title: "Settlement ba tare da spreadsheet ba: raba charge guda tsakanin masu karɓa da yawa" },
    "/concepts/hard-parts/scheduler-that-survives-a-crash": { title: "Gina mai tsara lokaci da ke tsira idan tsarin ya faɗi a tsakiyar aiki" },
    "/concepts/hard-parts/isolation-is-a-data-model-property": { title: "Rarrabuwa a matsayin sifar samfurin bayanai, ba binciken middleware ba" },
    "/concepts/hard-parts/what-to-check-before-you-trust-a-billing-layer": { title: "Abin da za ka duba kafin ka amince wa billing layer da kuɗin shigarka" },
    "/webhooks/overview": { title: "Bayani kan webhooks" },
    "/webhooks/signing-and-verification": { title: "Sa hannu da tantancewa" },
    "/webhooks/retries-and-replay": { title: "Sake gwadawa & replay" },
    "/webhooks/delivery-guarantee": { title: "Tabbacin delivery" },
    "/migrate/overview": { title: "Matsa zuwa Nomba One" },
    "/migrate/from-paystack": { title: "Barin subscriptions na Paystack" },
    "/migrate/from-stripe": { title: "Barin Stripe Billing zuwa tsarin da bai dogara ga rail guda ɗaya ba" },
    "/migrate/from-flutterwave": { title: "Ƙaura daga Flutterwave" },
    "/migrate/generic": { title: "Daga kowane processor" },
    "/merchants/overview": { title: "Gudanar da subscription ba tare da injiniya ba" },
    "/merchants/create-a-plan": { title: "Ƙirƙiri plan" },
    "/merchants/share-a-payment-link": { title: "Raba hanyar haɗin biyan kuɗi" },
    "/merchants/set-up-dunning-messages": { title: "Saita saƙonnin dunning" },
    "/merchants/read-a-settlement": { title: "Karanta settlement" },
    "": { title: "Nomba One" },
  },
};
