import type { NavOverlay } from "./types";

/**
 * GENERATED by `scripts/build-nav-overlay.ts` — do not edit `items` by hand.
 *
 * `items` is derived from each translated page's own frontmatter `title`, so a
 * sidebar label can never disagree with the page it opens. Re-run
 * `pnpm -F @nombaone/docs l10n:nav` after translating a page.
 *
 * `sections` IS hand-authored and is preserved across regeneration. Sections that
 * lead only to frozen-English pages keep their English titles on purpose.
 */
export const NAV_YO: NavOverlay = {
  sections: {
    "get-started": "Bẹ̀rẹ̀",
    libraries: "Quickstart",
    sdks: "SDKs & CLI",
    guides: "Àwọn ìtọ́sọ́nà",
    cookbook: "Cookbook",
    concepts: "Èròngbà",
    "best-practices": "Àwọn ìlànà tó dára jù",
    api: "API reference",
    webhooks: "Webhooks",
    errors: "Errors",
    "sandbox-toolkit": "Sandbox toolkit",
    changelog: "Release notes",
    migrate: "Ìṣíkiri",
    agents: "Fún àwọn agent",
    merchants: "Fún àwọn oníṣòwò",
  },
  items: {
    "/getting-started/authentication": { title: "Ìjẹ́rìísí" },
    "/getting-started/environments": { title: "Àwọn Àyíká" },
    "/getting-started/your-first-subscription": { title: "Subscription àkọ́kọ́ rẹ" },
    "/getting-started/verify-in-your-devtools": { title: "Ṣàyẹ̀wò wa nínú devtools rẹ" },
    "/getting-started/quickstart": { title: "Quickstart" },
    "/guides/create-plans-and-prices": { title: "Ṣẹ̀dá plan àti price" },
    "/guides/start-a-subscription": { title: "Bẹ̀rẹ̀ subscription kan" },
    "/guides/handle-webhooks": { title: "Ṣíṣàkóso webhooks" },
    "/guides/dunning-and-recovery": { title: "Dunning àti ìgbàpadà" },
    "/guides/refunds-payouts-settlement": { title: "Refunds, payouts àti settlement" },
    "/guides/proration-and-plan-changes": { title: "Proration àti àwọn ìyípadà plan" },
    "/guides/coupons-and-credits": { title: "Coupon àti credit" },
    "/guides/going-live": { title: "Lílọ sí live" },
    "/concepts/how-billing-works": { title: "Bí billing ṣe ń ṣiṣẹ́" },
    "/concepts/money-is-integer-kobo": { title: "Owó jẹ́ odidi kobo" },
    "/concepts/the-ledger": { title: "Ledger ìkọsílẹ̀ ẹ̀ẹ̀méjì" },
    "/concepts/multi-rail-push-and-pull": { title: "Multi-rail: push àti pull" },
    "/concepts/settlement-and-sub-accounts": { title: "Settlement àti sub-accounts" },
    "/concepts/hard-parts": { title: "Àwọn apá tó le" },
    "/concepts/hard-parts/the-double-charge-bug": { title: "Àṣìṣe gbígba owó lẹ́ẹ̀mejì, àti ìdí tí idempotency key kò fi jẹ́ àṣàyàn" },
    "/concepts/hard-parts/dunning-for-thin-balances": { title: "Dunning fún balance tí kò lówó: ìdí tí àtúngbìyànjú lọ́jọ́ owó-oṣù fi sàn ju àkókò tí a ti dì mọ́lẹ̀" },
    "/concepts/hard-parts/bank-transfer-is-not-just-another-method": { title: "Ìdí tí bank transfer kì í fi ṣe ọ̀nà ìsanwó lásán" },
    "/concepts/hard-parts/card-tokens-expire": { title: "Card token máa ń pàrí, àti ìdí tí àtúngbìyànjú afọ́jú fi ń fi àkókò dunning rẹ ṣòfò" },
    "/concepts/hard-parts/when-a-transfer-does-not-match-the-invoice": { title: "Nígbà tí owó tí a fi ránṣẹ́ kò bá iye invoice mu" },
    "/concepts/hard-parts/retry-the-webhook-is-not-retry-the-charge": { title: "\"Tún webhook náà rán\" kọ́ ni \"tún charge náà gbìyànjú\"" },
    "/concepts/hard-parts/mandates-and-consent": { title: "Mandate àti ìfọwọ́sí: ìrísí ìtẹ̀lé-òfin ti direct debit" },
    "/concepts/hard-parts/proration-is-a-ledger-problem": { title: "Proration jẹ́ ìṣòro ledger, kì í ṣe ìṣòro ìṣirò" },
    "/concepts/hard-parts/the-end-of-month-billing-trap": { title: "Ìdẹkùn ìsanwó ìparí-oṣù (ìṣòro ọjọ́ 31 January)" },
    "/concepts/hard-parts/voluntary-vs-involuntary-churn": { title: "Ìjáde-àtinúwá àti ìjáde-àìtinúwá, àti ìdí tí dídà wọn pọ̀ fi ń ba àwọn ìwọ̀n rẹ jẹ́" },
    "/concepts/hard-parts/settlement-without-spreadsheets": { title: "Settlement láìsí spreadsheet: pínpín charge kan sí ọ̀pọ̀ olùgbà owó" },
    "/concepts/hard-parts/scheduler-that-survives-a-crash": { title: "Kíkọ́ ètò ìṣèto-àkókò tí ó lè yè ìwólulẹ̀ láàárín iṣẹ́" },
    "/concepts/hard-parts/isolation-is-a-data-model-property": { title: "Ìyàsọ́tọ̀ gẹ́gẹ́ bí ànímọ́ àwòṣe dátà, kì í ṣe àyẹ̀wò middleware" },
    "/concepts/hard-parts/what-to-check-before-you-trust-a-billing-layer": { title: "Ohun tí o gbọ́dọ̀ yẹ̀wò kí o tó fi owó tí ń wọlé fún ọ lé ìpele billing lọ́wọ́" },
    "/webhooks/overview": { title: "Àkópọ̀ webhooks" },
    "/webhooks/signing-and-verification": { title: "Ìfọwọ́sí àti ìjẹ́rìísí" },
    "/webhooks/retries-and-replay": { title: "Àtúngbìyànjú & replay" },
    "/webhooks/delivery-guarantee": { title: "Ìdánilójú delivery" },
    "/migrate/overview": { title: "Ṣí lọ sí Nomba One" },
    "/migrate/from-paystack": { title: "Ìṣílọ kúrò nínú subscriptions Paystack" },
    "/migrate/from-stripe": { title: "Kíkúrò ní Stripe Billing sí àwòṣe tí kò gbára lé rail kan ṣoṣo" },
    "/migrate/from-flutterwave": { title: "Wíwá láti Flutterwave" },
    "/migrate/generic": { title: "Láti ara ẹ̀rọ ìsanwó èyíkéyìí" },
    "/merchants/overview": { title: "Ṣàkóso subscription láìsí onímọ̀ ẹ̀rọ" },
    "/merchants/create-a-plan": { title: "Dá plan sílẹ̀" },
    "/merchants/share-a-payment-link": { title: "Pín ìjápọ̀ ìsanwó" },
    "/merchants/set-up-dunning-messages": { title: "Ṣètò àwọn ìsọfúnni dunning" },
    "/merchants/read-a-settlement": { title: "Ka settlement kan" },
    "": { title: "Nomba One" },
  },
};
