/**
 * Generate the nav overlays (`content/l10n/nav.<locale>.ts`) from the translated
 * pages themselves.
 *
 * The sidebar label and the page's own `<h1>` MUST agree — a link that says
 * "Dunning and recovery" and opens a page titled "Dunning da farfaɗowar biyan
 * kuɗi" is a small lie the reader pays for on every click. Rather than maintain
 * a second list of titles by hand and hope it tracks, we derive the labels from
 * the one place that is already true: each translated file's frontmatter.
 *
 * Pages with NO translation are deliberately left out of the overlay. They fall
 * back to their English label — which is correct, because `href()` sends them to
 * the English page.
 *
 * Run: `pnpm -F @nombaone/docs l10n:nav`
 */

import { promises as fs } from "node:fs";
import path from "node:path";

import matter from "gray-matter";

import { MANIFEST } from "../content/manifest";
import { TRANSLATED_LOCALES, type TranslatedLocale } from "../src/lib/l10n/config";

const L10N_DIR = path.join(process.cwd(), "l10n");
const OUT_DIR = path.join(process.cwd(), "content", "l10n");

/**
 * Section titles are hand-authored (there are only 15, and several deliberately
 * stay English because they lead only to frozen-English pages). We read the
 * existing file's `sections` block and preserve it rather than clobber it.
 */
async function existingSections(locale: TranslatedLocale): Promise<string> {
  const file = path.join(OUT_DIR, `nav.${locale}.ts`);
  const src = await fs.readFile(file, "utf8");
  const match = /sections:\s*\{([\s\S]*?)\n  \},/.exec(src);
  if (!match) throw new Error(`could not find the sections block in ${file}`);
  return match[1];
}

async function listMdx(dir: string): Promise<string[]> {
  const out: string[] = [];
  try {
    for (const entry of await fs.readdir(dir, { withFileTypes: true })) {
      const full = path.join(dir, entry.name);
      if (entry.isDirectory()) out.push(...(await listMdx(full)));
      else if (entry.name.endsWith(".mdx")) out.push(full);
    }
  } catch {
    return [];
  }
  return out;
}

/** Manifest order, so the generated file is stable and diffs stay readable. */
function manifestOrder(): string[] {
  const slugs: string[] = [];
  for (const section of MANIFEST) {
    for (const item of section.items) {
      slugs.push(item.slug);
      for (const child of item.children ?? []) slugs.push(child.slug);
    }
  }
  return slugs;
}

const q = (s: string) => JSON.stringify(s);

async function build(locale: TranslatedLocale): Promise<number> {
  const root = path.join(L10N_DIR, locale);
  const files = await listMdx(root);

  const items = new Map<string, { title: string; summary?: string }>();
  for (const file of files) {
    const rel = path.relative(root, file).replace(/\.mdx$/, "");
    const slug = rel === "index" ? "" : `/${rel}`;
    const { data } = matter(await fs.readFile(file, "utf8"));
    if (typeof data.title !== "string") continue;
    items.set(slug, {
      title: data.title,
      summary: typeof data.description === "string" ? data.description : undefined,
    });
  }

  const order = manifestOrder();
  const ordered = [...items.keys()].sort((a, b) => {
    const ia = order.indexOf(a);
    const ib = order.indexOf(b);
    return (ia === -1 ? Infinity : ia) - (ib === -1 ? Infinity : ib);
  });

  const rows = ordered
    .map((slug) => {
      const entry = items.get(slug)!;
      // The manifest summary is a nav blurb, not the page's <meta> description.
      // Reusing the (long) description here would blow out the sidebar tooltip,
      // so titles only — summaries stay English until they are authored as nav copy.
      return `    ${q(slug)}: { title: ${q(entry.title)} },`;
    })
    .join("\n");

  const NAME = locale.toUpperCase();
  const source = `import type { NavOverlay } from "./types";

/**
 * GENERATED by \`scripts/build-nav-overlay.ts\` — do not edit \`items\` by hand.
 *
 * \`items\` is derived from each translated page's own frontmatter \`title\`, so a
 * sidebar label can never disagree with the page it opens. Re-run
 * \`pnpm -F @nombaone/docs l10n:nav\` after translating a page.
 *
 * \`sections\` IS hand-authored and is preserved across regeneration. Sections that
 * lead only to frozen-English pages keep their English titles on purpose.
 */
export const NAV_${NAME}: NavOverlay = {
  sections: {${await existingSections(locale)}
  },
  items: {
${rows}
  },
};
`;

  await fs.writeFile(path.join(OUT_DIR, `nav.${locale}.ts`), source, "utf8");
  return ordered.length;
}

async function main() {
  for (const locale of TRANSLATED_LOCALES) {
    const count = await build(locale);
    console.log(`[l10n:nav] ${locale}: ${count} nav labels → content/l10n/nav.${locale}.ts`);
  }
}

main().catch((error) => {
  console.error("[l10n:nav] failed:", error);
  process.exit(1);
});
