export type ApiFieldErrors = Record<string, string[]>;

export const HTTP_SUCCESS_STATUS_CODES = {
  OK: 200,
  CREATED: 201,
  ACCEPTED: 202,
  NO_CONTENT: 204,
} as const;

export const HTTP_REDIRECT_STATUS_CODES = {
  MULTIPLE_CHOICES: 300,
  MOVED_PERMANENTLY: 301,
  FOUND: 302,
  SEE_OTHER: 303,
  NOT_MODIFIED: 304,
  TEMPORARY_REDIRECT: 307,
  PERMANENT_REDIRECT: 308,
} as const;

export const HTTP_ERROR_STATUS_CODES = {
  BAD_REQUEST: 400,
  UNAUTHORIZED: 401,
  FORBIDDEN: 403,
  NOT_FOUND: 404,
  CONFLICT: 409,
  UNPROCESSABLE_ENTITY: 422,
  TOO_MANY_REQUESTS: 429,
  INTERNAL_SERVER_ERROR: 500,
  BAD_GATEWAY: 502,
  SERVICE_UNAVAILABLE: 503,
  GATEWAY_TIMEOUT: 504,
} as const;

export const HTTP_STATUS_CODES = {
  ...HTTP_SUCCESS_STATUS_CODES,
  ...HTTP_REDIRECT_STATUS_CODES,
  ...HTTP_ERROR_STATUS_CODES,
} as const;

/**
 * The central error-code enum, shared across every package and app (backend +
 * frontends). It is intentionally GENERIC platform vocabulary — there is no
 * billing-product code here (no plan/subscription/invoice/dunning codes). Add
 * domain codes alongside the domain you build.
 *
 * Naming family → meaning:
 *  - `CLIENT_*`        bad request shapes from an API caller
 *  - `API_KEY_*`       public-API authentication (the per-org secret key)
 *  - `AUTH_*`          console/operator session authentication
 *  - `ORG_*`/`MEMBER_*`identity & membership
 *  - `IDEMPOTENCY_*`   the idempotency state machine
 *  - `WEBHOOK_*`       inbound (provider→us) + outbound (us→tenant) webhooks
 *  - `LEDGER_*`        double-entry ledger invariants
 *  - `RAIL_*`          the payment-rail abstraction
 *  - `SYSTEM_*`        internal / upstream failures (the public fallback)
 *
 * Internal codes never leak: the error handler collapses anything not in
 * `PUBLIC_ERROR_CODES` to `SYSTEM_INTERNAL_ERROR` on the wire.
 */
export const NOMBAONE_ERROR_CODES = {
  // ---- Generic client request errors ----
  CLIENT_INVALID_REQUEST: 'CLIENT_INVALID_REQUEST',
  CLIENT_VALIDATION_FAILED: 'CLIENT_VALIDATION_FAILED',
  CLIENT_FORBIDDEN: 'CLIENT_FORBIDDEN',
  CLIENT_ROUTE_NOT_FOUND: 'CLIENT_ROUTE_NOT_FOUND',
  CLIENT_RESOURCE_NOT_FOUND: 'CLIENT_RESOURCE_NOT_FOUND',
  CLIENT_CONFLICT: 'CLIENT_CONFLICT',
  INVALID_CURSOR: 'INVALID_CURSOR',

  // ---- Public-API auth (per-org secret API key) ----
  API_KEY_MISSING: 'API_KEY_MISSING',
  API_KEY_INVALID: 'API_KEY_INVALID',
  API_KEY_SCOPE_FORBIDDEN: 'API_KEY_SCOPE_FORBIDDEN',
  API_KEY_ENVIRONMENT_MISMATCH: 'API_KEY_ENVIRONMENT_MISMATCH',

  // ---- Console / operator session auth ----
  AUTH_INVALID_CREDENTIALS: 'AUTH_INVALID_CREDENTIALS',
  AUTH_EMAIL_TAKEN: 'AUTH_EMAIL_TAKEN',
  AUTH_SESSION_INVALID: 'AUTH_SESSION_INVALID',
  AUTH_TOTP_REQUIRED: 'AUTH_TOTP_REQUIRED',
  AUTH_TOTP_INVALID: 'AUTH_TOTP_INVALID',
  AUTH_TOTP_NOT_ENROLLED: 'AUTH_TOTP_NOT_ENROLLED',
  AUTH_FORBIDDEN_ROLE: 'AUTH_FORBIDDEN_ROLE',
  AUTH_PASSWORD_INCORRECT: 'AUTH_PASSWORD_INCORRECT',
  AUTH_RESET_TOKEN_INVALID: 'AUTH_RESET_TOKEN_INVALID',

  // ---- Identity & membership ----
  ORG_NOT_FOUND: 'ORG_NOT_FOUND',
  INVITE_INVALID: 'INVITE_INVALID',
  INVITE_EMAIL_ACTIVE: 'INVITE_EMAIL_ACTIVE',
  MEMBER_NOT_FOUND: 'MEMBER_NOT_FOUND',
  MEMBER_LAST_OWNER: 'MEMBER_LAST_OWNER',

  // ---- Idempotency state machine ----
  IDEMPOTENCY_KEY_MISSING: 'IDEMPOTENCY_KEY_MISSING',
  IDEMPOTENCY_KEY_REUSED: 'IDEMPOTENCY_KEY_REUSED',
  IDEMPOTENCY_IN_PROGRESS: 'IDEMPOTENCY_IN_PROGRESS',

  // ---- Rate limiting ----
  RATE_LIMIT_EXCEEDED: 'RATE_LIMIT_EXCEEDED',

  // ---- Platform gate / maintenance ----
  PLATFORM_MAINTENANCE: 'PLATFORM_MAINTENANCE',

  // ---- Webhooks (inbound provider→us, outbound us→tenant) ----
  WEBHOOK_SIGNATURE_INVALID: 'WEBHOOK_SIGNATURE_INVALID',
  WEBHOOK_DUPLICATE_EVENT: 'WEBHOOK_DUPLICATE_EVENT',
  WEBHOOK_RAW_BODY_MISSING: 'WEBHOOK_RAW_BODY_MISSING',
  WEBHOOK_ENDPOINT_NOT_FOUND: 'WEBHOOK_ENDPOINT_NOT_FOUND',
  WEBHOOK_EVENT_NOT_FOUND: 'WEBHOOK_EVENT_NOT_FOUND',

  // ---- Double-entry ledger ----
  LEDGER_TRANSACTION_UNBALANCED: 'LEDGER_TRANSACTION_UNBALANCED',
  LEDGER_INVALID_ENTRY: 'LEDGER_INVALID_ENTRY',
  LEDGER_ACCOUNT_NOT_FOUND: 'LEDGER_ACCOUNT_NOT_FOUND',
  LEDGER_TRANSACTION_NOT_FOUND: 'LEDGER_TRANSACTION_NOT_FOUND',
  LEDGER_TRANSACTION_ALREADY_REVERSED: 'LEDGER_TRANSACTION_ALREADY_REVERSED',
  LEDGER_INSUFFICIENT_FUNDS: 'LEDGER_INSUFFICIENT_FUNDS',

  // ---- Reconciliation ----
  RECONCILIATION_DRIFT_DETECTED: 'RECONCILIATION_DRIFT_DETECTED',

  // ---- Payment-rail abstraction ----
  RAIL_NOT_REGISTERED: 'RAIL_NOT_REGISTERED',
  RAIL_NOT_SUPPORTED: 'RAIL_NOT_SUPPORTED',

  // ---- Customers ----
  CUSTOMER_NOT_FOUND: 'CUSTOMER_NOT_FOUND',
  CUSTOMER_EMAIL_TAKEN: 'CUSTOMER_EMAIL_TAKEN',

  // ---- Catalog: plans & prices ----
  PLAN_NOT_FOUND: 'PLAN_NOT_FOUND',
  PLAN_NAME_TAKEN: 'PLAN_NAME_TAKEN',
  PLAN_ALREADY_ARCHIVED: 'PLAN_ALREADY_ARCHIVED',
  PLAN_HAS_ACTIVE_SUBSCRIBERS: 'PLAN_HAS_ACTIVE_SUBSCRIBERS',
  PRICE_NOT_FOUND: 'PRICE_NOT_FOUND',
  PRICE_PLAN_MISMATCH: 'PRICE_PLAN_MISMATCH',
  PRICE_IMMUTABLE: 'PRICE_IMMUTABLE',
  PRICE_ALREADY_INACTIVE: 'PRICE_ALREADY_INACTIVE',
  PRICE_TIERED_NOT_SUPPORTED: 'PRICE_TIERED_NOT_SUPPORTED',
  CATALOG_INVALID_INTERVAL: 'CATALOG_INVALID_INTERVAL',

  // ---- Payment methods, mandates & the Nomba provider ----
  PAYMENT_METHOD_NOT_FOUND: 'PAYMENT_METHOD_NOT_FOUND',
  PAYMENT_METHOD_NOT_ACTIVE: 'PAYMENT_METHOD_NOT_ACTIVE',
  PAYMENT_METHOD_KIND_MISMATCH: 'PAYMENT_METHOD_KIND_MISMATCH',
  MANDATE_NOT_ACTIVE: 'MANDATE_NOT_ACTIVE',
  MANDATE_MAX_AMOUNT_EXCEEDED: 'MANDATE_MAX_AMOUNT_EXCEEDED',
  MANDATE_CONSENT_PENDING: 'MANDATE_CONSENT_PENDING',
  NOMBA_REQUEST_FAILED: 'NOMBA_REQUEST_FAILED',
  NOMBA_UNAUTHORIZED: 'NOMBA_UNAUTHORIZED',
  NOMBA_SIGNATURE_INVALID: 'NOMBA_SIGNATURE_INVALID',

  // ---- Subscriptions & invoices ----
  SUBSCRIPTION_NOT_FOUND: 'SUBSCRIPTION_NOT_FOUND',
  SUBSCRIPTION_ILLEGAL_TRANSITION: 'SUBSCRIPTION_ILLEGAL_TRANSITION',
  SUBSCRIPTION_VERSION_CONFLICT: 'SUBSCRIPTION_VERSION_CONFLICT',
  SUBSCRIPTION_NOT_TERMINAL: 'SUBSCRIPTION_NOT_TERMINAL',
  SUBSCRIPTION_PAYMENT_METHOD_REQUIRED: 'SUBSCRIPTION_PAYMENT_METHOD_REQUIRED',
  INVOICE_NOT_FOUND: 'INVOICE_NOT_FOUND',
  INVOICE_ALREADY_FINALIZED: 'INVOICE_ALREADY_FINALIZED',
  INVOICE_ALREADY_PAID: 'INVOICE_ALREADY_PAID',
  INVOICE_NOT_VOIDABLE: 'INVOICE_NOT_VOIDABLE',
  INVOICE_LINE_ITEMS_UNBALANCED: 'INVOICE_LINE_ITEMS_UNBALANCED',

  // ---- Billing scheduler & schedules (04) ----
  SUBSCRIPTION_SCHEDULE_NOT_FOUND: 'SUBSCRIPTION_SCHEDULE_NOT_FOUND',
  SUBSCRIPTION_SCHEDULE_CONFLICT: 'SUBSCRIPTION_SCHEDULE_CONFLICT',
  SUBSCRIPTION_SCHEDULE_INVALID_EFFECTIVE_AT: 'SUBSCRIPTION_SCHEDULE_INVALID_EFFECTIVE_AT',
  BILLING_CATCH_UP_LIMIT_EXCEEDED: 'BILLING_CATCH_UP_LIMIT_EXCEEDED',

  // ---- Invoicing adjustments (05): proration / coupons / discounts / credits ----
  PRORATION_NOT_APPLICABLE: 'PRORATION_NOT_APPLICABLE',
  PRORATION_PERIOD_INVALID: 'PRORATION_PERIOD_INVALID',
  PRORATION_DISTRIBUTION_UNBALANCED: 'PRORATION_DISTRIBUTION_UNBALANCED',
  PRORATION_INTERVAL_SWITCH_UNSUPPORTED: 'PRORATION_INTERVAL_SWITCH_UNSUPPORTED',
  COUPON_NOT_FOUND: 'COUPON_NOT_FOUND',
  COUPON_EXPIRED: 'COUPON_EXPIRED',
  COUPON_MAX_REDEMPTIONS_REACHED: 'COUPON_MAX_REDEMPTIONS_REACHED',
  COUPON_INVALID_DEFINITION: 'COUPON_INVALID_DEFINITION',
  COUPON_ALREADY_APPLIED: 'COUPON_ALREADY_APPLIED',
  DISCOUNT_NOT_FOUND: 'DISCOUNT_NOT_FOUND',
  CREDIT_GRANT_NOT_FOUND: 'CREDIT_GRANT_NOT_FOUND',
  CREDIT_INSUFFICIENT_BALANCE: 'CREDIT_INSUFFICIENT_BALANCE',
  CREDIT_INVALID_AMOUNT: 'CREDIT_INVALID_AMOUNT',
  INVOICE_NOT_BALANCED: 'INVOICE_NOT_BALANCED',

  // ---- Dunning & recovery (06) ----
  DUNNING_SETTINGS_INVALID: 'DUNNING_SETTINGS_INVALID',
  DUNNING_NO_OPEN_INVOICE: 'DUNNING_NO_OPEN_INVOICE',
  DUNNING_ALREADY_TERMINAL: 'DUNNING_ALREADY_TERMINAL',
  DUNNING_ATTEMPT_NOT_FOUND: 'DUNNING_ATTEMPT_NOT_FOUND',
  DUNNING_CARD_UPDATE_REQUIRED: 'DUNNING_CARD_UPDATE_REQUIRED',
  DUNNING_NOT_IN_PROGRESS: 'DUNNING_NOT_IN_PROGRESS',

  // ---- The deletable example slice (delete with the example) ----
  EXAMPLE_NOT_FOUND: 'EXAMPLE_NOT_FOUND',

  // ---- Internal / upstream (public fallbacks) ----
  SYSTEM_INTERNAL_ERROR: 'SYSTEM_INTERNAL_ERROR',
  SYSTEM_UPSTREAM_ERROR: 'SYSTEM_UPSTREAM_ERROR',
} as const;

export type HttpSuccessStatusCode =
  (typeof HTTP_SUCCESS_STATUS_CODES)[keyof typeof HTTP_SUCCESS_STATUS_CODES];
export type HttpRedirectStatusCode =
  (typeof HTTP_REDIRECT_STATUS_CODES)[keyof typeof HTTP_REDIRECT_STATUS_CODES];
export type HttpErrorStatusCode =
  (typeof HTTP_ERROR_STATUS_CODES)[keyof typeof HTTP_ERROR_STATUS_CODES];

export type NombaoneErrorCode = (typeof NOMBAONE_ERROR_CODES)[keyof typeof NOMBAONE_ERROR_CODES];

export const getDefaultNombaoneErrorCodeForStatus = (
  status: HttpErrorStatusCode
): NombaoneErrorCode => {
  switch (status) {
    case HTTP_STATUS_CODES.BAD_REQUEST:
      return NOMBAONE_ERROR_CODES.CLIENT_INVALID_REQUEST;
    case HTTP_STATUS_CODES.UNAUTHORIZED:
      return NOMBAONE_ERROR_CODES.API_KEY_INVALID;
    case HTTP_STATUS_CODES.FORBIDDEN:
      return NOMBAONE_ERROR_CODES.CLIENT_FORBIDDEN;
    case HTTP_STATUS_CODES.NOT_FOUND:
      return NOMBAONE_ERROR_CODES.CLIENT_RESOURCE_NOT_FOUND;
    case HTTP_STATUS_CODES.CONFLICT:
      return NOMBAONE_ERROR_CODES.CLIENT_CONFLICT;
    case HTTP_STATUS_CODES.UNPROCESSABLE_ENTITY:
      return NOMBAONE_ERROR_CODES.CLIENT_VALIDATION_FAILED;
    case HTTP_STATUS_CODES.TOO_MANY_REQUESTS:
      return NOMBAONE_ERROR_CODES.RATE_LIMIT_EXCEEDED;
    case HTTP_STATUS_CODES.BAD_GATEWAY:
    case HTTP_STATUS_CODES.SERVICE_UNAVAILABLE:
    case HTTP_STATUS_CODES.GATEWAY_TIMEOUT:
      return NOMBAONE_ERROR_CODES.SYSTEM_UPSTREAM_ERROR;
    case HTTP_STATUS_CODES.INTERNAL_SERVER_ERROR:
    default:
      return NOMBAONE_ERROR_CODES.SYSTEM_INTERNAL_ERROR;
  }
};

/**
 * Codes safe to expose on the public API wire. Anything NOT here is collapsed to
 * `SYSTEM_INTERNAL_ERROR` by the error handler so internal detail never leaks.
 */
export const PUBLIC_ERROR_CODES: ReadonlySet<NombaoneErrorCode> = new Set([
  NOMBAONE_ERROR_CODES.CLIENT_INVALID_REQUEST,
  NOMBAONE_ERROR_CODES.CLIENT_VALIDATION_FAILED,
  NOMBAONE_ERROR_CODES.CLIENT_FORBIDDEN,
  NOMBAONE_ERROR_CODES.CLIENT_ROUTE_NOT_FOUND,
  NOMBAONE_ERROR_CODES.CLIENT_RESOURCE_NOT_FOUND,
  NOMBAONE_ERROR_CODES.CLIENT_CONFLICT,
  NOMBAONE_ERROR_CODES.INVALID_CURSOR,
  NOMBAONE_ERROR_CODES.API_KEY_MISSING,
  NOMBAONE_ERROR_CODES.API_KEY_INVALID,
  NOMBAONE_ERROR_CODES.API_KEY_SCOPE_FORBIDDEN,
  NOMBAONE_ERROR_CODES.API_KEY_ENVIRONMENT_MISMATCH,
  NOMBAONE_ERROR_CODES.IDEMPOTENCY_KEY_MISSING,
  NOMBAONE_ERROR_CODES.IDEMPOTENCY_KEY_REUSED,
  NOMBAONE_ERROR_CODES.IDEMPOTENCY_IN_PROGRESS,
  NOMBAONE_ERROR_CODES.RATE_LIMIT_EXCEEDED,
  NOMBAONE_ERROR_CODES.PLATFORM_MAINTENANCE,
  NOMBAONE_ERROR_CODES.WEBHOOK_SIGNATURE_INVALID,
  NOMBAONE_ERROR_CODES.CUSTOMER_NOT_FOUND,
  NOMBAONE_ERROR_CODES.CUSTOMER_EMAIL_TAKEN,
  NOMBAONE_ERROR_CODES.PLAN_NOT_FOUND,
  NOMBAONE_ERROR_CODES.PLAN_NAME_TAKEN,
  NOMBAONE_ERROR_CODES.PLAN_ALREADY_ARCHIVED,
  NOMBAONE_ERROR_CODES.PLAN_HAS_ACTIVE_SUBSCRIBERS,
  NOMBAONE_ERROR_CODES.PRICE_NOT_FOUND,
  NOMBAONE_ERROR_CODES.PRICE_PLAN_MISMATCH,
  NOMBAONE_ERROR_CODES.PRICE_ALREADY_INACTIVE,
  NOMBAONE_ERROR_CODES.PRICE_TIERED_NOT_SUPPORTED,
  NOMBAONE_ERROR_CODES.PAYMENT_METHOD_NOT_FOUND,
  NOMBAONE_ERROR_CODES.PAYMENT_METHOD_NOT_ACTIVE,
  NOMBAONE_ERROR_CODES.PAYMENT_METHOD_KIND_MISMATCH,
  NOMBAONE_ERROR_CODES.MANDATE_NOT_ACTIVE,
  NOMBAONE_ERROR_CODES.MANDATE_MAX_AMOUNT_EXCEEDED,
  NOMBAONE_ERROR_CODES.MANDATE_CONSENT_PENDING,
  NOMBAONE_ERROR_CODES.SUBSCRIPTION_NOT_FOUND,
  NOMBAONE_ERROR_CODES.SUBSCRIPTION_ILLEGAL_TRANSITION,
  NOMBAONE_ERROR_CODES.SUBSCRIPTION_VERSION_CONFLICT,
  NOMBAONE_ERROR_CODES.SUBSCRIPTION_NOT_TERMINAL,
  NOMBAONE_ERROR_CODES.SUBSCRIPTION_PAYMENT_METHOD_REQUIRED,
  NOMBAONE_ERROR_CODES.INVOICE_NOT_FOUND,
  NOMBAONE_ERROR_CODES.INVOICE_ALREADY_FINALIZED,
  NOMBAONE_ERROR_CODES.INVOICE_ALREADY_PAID,
  NOMBAONE_ERROR_CODES.INVOICE_NOT_VOIDABLE,
  NOMBAONE_ERROR_CODES.SUBSCRIPTION_SCHEDULE_NOT_FOUND,
  NOMBAONE_ERROR_CODES.SUBSCRIPTION_SCHEDULE_CONFLICT,
  NOMBAONE_ERROR_CODES.SUBSCRIPTION_SCHEDULE_INVALID_EFFECTIVE_AT,
  NOMBAONE_ERROR_CODES.PRORATION_NOT_APPLICABLE,
  NOMBAONE_ERROR_CODES.PRORATION_INTERVAL_SWITCH_UNSUPPORTED,
  NOMBAONE_ERROR_CODES.COUPON_NOT_FOUND,
  NOMBAONE_ERROR_CODES.COUPON_EXPIRED,
  NOMBAONE_ERROR_CODES.COUPON_MAX_REDEMPTIONS_REACHED,
  NOMBAONE_ERROR_CODES.COUPON_INVALID_DEFINITION,
  NOMBAONE_ERROR_CODES.COUPON_ALREADY_APPLIED,
  NOMBAONE_ERROR_CODES.DISCOUNT_NOT_FOUND,
  NOMBAONE_ERROR_CODES.CREDIT_GRANT_NOT_FOUND,
  NOMBAONE_ERROR_CODES.CREDIT_INSUFFICIENT_BALANCE,
  NOMBAONE_ERROR_CODES.CREDIT_INVALID_AMOUNT,
  NOMBAONE_ERROR_CODES.DUNNING_NO_OPEN_INVOICE,
  NOMBAONE_ERROR_CODES.DUNNING_ATTEMPT_NOT_FOUND,
  NOMBAONE_ERROR_CODES.DUNNING_CARD_UPDATE_REQUIRED,
  NOMBAONE_ERROR_CODES.DUNNING_ALREADY_TERMINAL,
  NOMBAONE_ERROR_CODES.EXAMPLE_NOT_FOUND,
  NOMBAONE_ERROR_CODES.SYSTEM_INTERNAL_ERROR,
  NOMBAONE_ERROR_CODES.SYSTEM_UPSTREAM_ERROR,
]);

export const toPublicErrorCode = (code: NombaoneErrorCode): NombaoneErrorCode =>
  PUBLIC_ERROR_CODES.has(code) ? code : NOMBAONE_ERROR_CODES.SYSTEM_INTERNAL_ERROR;
