import { eq } from 'drizzle-orm';

import { orgUsersTable, type OrgUserRow } from '@nombaone/core-db/schema';

import { mintReference } from '../reference';
import { encryptPii } from '../crypto';
import { hashPassword } from './password';

import type { InfraReadScope, InfraTxScope } from '../context';
import type { OrgUserRole } from './rbac';

/**
 * PARADIGM — the console-user repository. A console user belongs to exactly ONE
 * organization (the tenant), so there is no global user table to deduplicate
 * across orgs; the `email` UNIQUE index is platform-wide and is the authority on
 * "is this email taken". These helpers are the only place that knows the row
 * shape of `org_users`: callers (signup, login, password-reset) speak in domain
 * verbs and never hand-roll inserts, so the password-hash / encrypted-TOTP
 * invariants are guaranteed by construction.
 */

/** Look up a user by email (already normalized lowercase by the validation layer). */
export const findUserByEmail = async (
  db: InfraReadScope,
  email: string
): Promise<OrgUserRow | null> => {
  const [row] = await db
    .select()
    .from(orgUsersTable)
    .where(eq(orgUsersTable.email, email))
    .limit(1);
  return row ?? null;
};

/** Look up a user by internal id. */
export const findUserById = async (db: InfraReadScope, userId: string): Promise<OrgUserRow | null> => {
  const [row] = await db.select().from(orgUsersTable).where(eq(orgUsersTable.id, userId)).limit(1);
  return row ?? null;
};

/**
 * Insert an org user. The password arrives in the clear and is hashed HERE so a
 * caller can never accidentally persist plaintext. Returns the full row (the
 * minted reference is the merchant-facing id).
 */
export const createOrgUser = async (
  txDb: InfraTxScope,
  params: {
    organizationId: string;
    email: string;
    name: string;
    password: string;
    role: OrgUserRole;
  }
): Promise<OrgUserRow> => {
  const passwordHash = await hashPassword(params.password);

  const [row] = await txDb
    .insert(orgUsersTable)
    .values({
      reference: mintReference('USR'),
      organizationId: params.organizationId,
      email: params.email,
      name: params.name,
      role: params.role,
      passwordHash,
    })
    .returning();

  return row as OrgUserRow;
};

/** Replace a user's password hash (re-hashing the new plaintext here). */
export const updateUserPassword = async (
  db: InfraTxScope,
  userId: string,
  newPassword: string
): Promise<void> => {
  const passwordHash = await hashPassword(newPassword);
  await db.update(orgUsersTable).set({ passwordHash }).where(eq(orgUsersTable.id, userId));
};

/**
 * Enroll TOTP: store the secret ENCRYPTED at rest and flip the enabled flag. The
 * secret is generated by `totp.generateTotpSecret()`; this helper owns only the
 * encrypt-and-persist step so the plaintext secret never lands in a column.
 */
export const enrollUserTotp = async (
  db: InfraTxScope,
  userId: string,
  secret: string
): Promise<void> => {
  await db
    .update(orgUsersTable)
    .set({ totpSecretEncrypted: encryptPii(secret), totpEnabled: true })
    .where(eq(orgUsersTable.id, userId));
};
